/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.cihangll.gui;

import javax.swing.JComboBox;

import com.cihangll.main.Variables;
import com.cihangll.services.CalculatorServiceImpl;
import com.cihangll.services.ConverterServiceImpl;

/**
 *
 * @author yakup
 */
public class main extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

    /**
     * Creates new form main
     */
    public main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sicaklikTf = new javax.swing.JTextField();
        yukseklikTf = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        maddeTuruCb = new javax.swing.JComboBox<String>();
        sicaklikTuruCb = new javax.swing.JComboBox<String>();
        yukseklikTuruCb = new javax.swing.JComboBox<String>();
        sicaklik = new javax.swing.JLabel();
        basinc = new javax.swing.JLabel();
        yogunluk = new javax.swing.JLabel();
        seshizi = new javax.swing.JLabel();
        viskozite = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("ATMOSFER BASINCI HESABI");

        jLabel3.setText("Sýcaklýk:");

        jLabel4.setText("Yükseklik:");

        sicaklikTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sicaklikTfActionPerformed(evt);
            }
        });

        jLabel1.setText("Sonuçlar");

        jLabel5.setText("Sýcaklýk:");

        jLabel6.setText("Basýnç:");

        jLabel7.setText("Yoðunluk:");

        jLabel8.setText("Madde Türü");

        jLabel9.setText("Ses Hýzý:");

        jLabel10.setText("Viskozite:");

        jButton1.setText("Hesapla");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        maddeTuruCb.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Hava", "Azot", "Oksijen", "Karbondioksit", "Karbonmonoksit", "Hidrojen", "Amonyak", "Kükürtdioksit" }));
        maddeTuruCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maddeTuruCbActionPerformed(evt);
            }
        });
        maddeTuruCb.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                maddeTuruCbPropertyChange(evt);
            }
        });

        sicaklikTuruCb.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Celcius", "Kelvin"}));
        sicaklikTuruCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sicaklikTuruCbActionPerformed(evt);
            }
        });
        sicaklikTuruCb.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                sicaklikTuruCbPropertyChange(evt);
            }
        });

        yukseklikTuruCb.setModel(new javax.swing.DefaultComboBoxModel<String>(new String[] { "Feet", "Meter"}));
        yukseklikTuruCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yukseklikTuruCbActionPerformed(evt);
            }
        });
        yukseklikTuruCb.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                yukseklikTuruCbPropertyChange(evt);
            }
        });

        sicaklik.setText("0");

        basinc.setText("0");

        yogunluk.setText("0");

        seshizi.setText("0");

        viskozite.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(19, 19, 19)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel5))
                                    .addGap(9, 9, 9)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(11, 11, 11)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(viskozite, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(sicaklikTf, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                                        .addComponent(yukseklikTf))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sicaklikTuruCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(yukseklikTuruCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(38, 38, 38)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addGap(18, 18, 18)
                                            .addComponent(maddeTuruCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(sicaklik, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(basinc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(yogunluk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(seshizi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(sicaklikTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(maddeTuruCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sicaklikTuruCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(yukseklikTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(yukseklikTuruCb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(sicaklik))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(basinc))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(yogunluk))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(seshizi))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(viskozite))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sicaklikTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sicaklikTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sicaklikTfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

       CalculatorServiceImpl calculator = new CalculatorServiceImpl(valueHeight, valueTemperature, typeValue);
       
       
       sicaklik.setText(String.valueOf(calculator.temperatureCalculationCelcius()));
       basinc.setText(String.valueOf(calculator.pressureCalculate()));
       yogunluk.setText(String.valueOf(calculator.densityCalculate()));
       seshizi.setText(String.valueOf(calculator.speedOfSoundCalculate()));
       viskozite.setText(String.valueOf(calculator.viscosityCalculate()));
    }//GEN-LAST:event_jButton1ActionPerformed

    Double typeValue = Variables.getAirSpeedOfSound();
    
    private void maddeTuruCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maddeTuruCbActionPerformed
        // TODO add your handling code here:
        JComboBox type = (JComboBox) evt.getSource();
        String typeName = (String) type.getSelectedItem();
        
        switch(typeName) {
            case "Hava":
                typeValue = Variables.getTemperatureAirReference();
                break;
            case "Azot":
                typeValue = Variables.getAzot_ref();
                break;
            case "Oksijen":
                typeValue = Variables.getOksijen_ref();
                break;
            case "Karbondioksit":
                typeValue = Variables.getKarbondioksit_ref();
                break;
            case "Karbonmonoksit":
                typeValue = Variables.getKarbonmonoksit_ref();
                break;
            case "Hidrojen":
                typeValue = Variables.getHidrojen_ref();
                break;
            case "Amonyak":
                typeValue = Variables.getAmonyak_ref();
                break;
            case "KÃ¼kÃ¼rtdioksit":
                typeValue = Variables.getKukurtdioksit_ref();
                break;
            default:
                typeValue = Variables.getTemperatureAirReference();
                break;
        }
    }//GEN-LAST:event_maddeTuruCbActionPerformed

    Double valueTemperature = 0.0;
    
    private void sicaklikTuruCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sicaklikTuruCbActionPerformed
        // TODO add your handling code here:
        JComboBox type = (JComboBox) evt.getSource();
        String typeName = (String) type.getSelectedItem();
        
        ConverterServiceImpl converter = new ConverterServiceImpl();
        
        if(typeName.equals("Kelvin")) {
            valueTemperature = converter.kelvinToCelsius(Double.parseDouble(sicaklikTf.getText()));
        }
        if(typeName.equals("Celcius")) {
            valueTemperature = Double.parseDouble(sicaklikTf.getText());
        }
    }//GEN-LAST:event_sicaklikTuruCbActionPerformed

    Double valueHeight = 0.0;
    private void yukseklikTuruCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yukseklikTuruCbActionPerformed
        // TODO add your handling code here:
        JComboBox type = (JComboBox) evt.getSource();
        String typeName = (String) type.getSelectedItem();
        
        ConverterServiceImpl converter = new ConverterServiceImpl();
        
        if(typeName.equals("Meter")) {
            valueHeight = converter.meterToFeet(Double.parseDouble(yukseklikTf.getText()));
        }
        if(typeName.equals("Feet")) {
            valueHeight = Double.parseDouble(yukseklikTf.getText());
        }
    }//GEN-LAST:event_yukseklikTuruCbActionPerformed

    private void maddeTuruCbPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_maddeTuruCbPropertyChange

    }//GEN-LAST:event_maddeTuruCbPropertyChange

    private void yukseklikTuruCbPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_yukseklikTuruCbPropertyChange

    }//GEN-LAST:event_yukseklikTuruCbPropertyChange

    private void sicaklikTuruCbPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_sicaklikTuruCbPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_sicaklikTuruCbPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel basinc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> maddeTuruCb;
    private javax.swing.JLabel seshizi;
    private javax.swing.JLabel sicaklik;
    private javax.swing.JTextField sicaklikTf;
    private javax.swing.JComboBox<String> sicaklikTuruCb;
    private javax.swing.JLabel viskozite;
    private javax.swing.JLabel yogunluk;
    private javax.swing.JTextField yukseklikTf;
    private javax.swing.JComboBox<String> yukseklikTuruCb;
    // End of variables declaration//GEN-END:variables
}
